class MedicalRecord < ApplicationRecord

  validates :temperature, presence: true
  validates :notes, presence: true
  validates :medications, presence: true
  validates :eyesText, presence: true
  validates :oral, presence: true
  validates :ears, presence: true
  validates :glands, presence: true
  validates :skin, presence: true
  validates :abdomen, presence: true
  validates :urogential, presence: true
  validates :nervousSystem, presence: true
  validates :musculoskeletal, presence: true
  validates :cardiovascular, presence: true
  validates :heart_rate, presence: true
  validates :respiratory, presence: true
  validates :respiratory_rate, presence: true
  validates :attitudeBAR, presence: true
  validates :attitudeQAR, presence: true
  validates :attitudeDepressed, presence: true
  validates :eyesN, presence: true
  validates :eyesA, presence: true
  validates :mmN, presence: true
  validates :mmPale, presence: true
  validates :mmJaundiced, presence: true
  validates :mmTacky, presence: true
  validates :earsN, presence: true
  validates :earsA, presence: true
  validates :earsEarMites, presence: true
  validates :earsAU, presence: true
  validates :earsAD, presence: true
  validates :earsAS, presence: true
  validates :glandsN, presence: true
  validates :glandsA, presence: true
  validates :skinN, presence: true
  validates :skinA, presence: true
  validates :abdomenN, presence: true
  validates :abdomenA, presence: true
  validates :urogentialN, presence: true
  validates :urogentialA, presence: true
  validates :nervousSystemN, presence: true
  validates :nervousSystemA, presence: true
  validates :musculoskeletalN, presence: true
  validates :musculoskeletalA, presence: true
  validates :cardiovascularN, presence: true
  validates :cardiovascularA, presence: true
  validates :respiratoryN, presence: true
  validates :respiratoryA, presence: true
end
